"""made survey stand alone


Revision ID: 3a621cd98d65
Revises: 2543f208af67
Create Date: 2019-01-31 12:48:09.095008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a621cd98d65'
down_revision = '2543f208af67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'survey', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
